export const products =[{
        id:1,
        image: 'images/bags2.jfif',
        name: 'Stripped Brown bag with gold chain handle',
        price: 25000
},{
        id:2,
        image :'images/bag4.webp',
        name:'bag',
        price:20000
        
    },
    {
        id:3,
        image: "images/bucketbag.webp",
        name:"bag",
        price:20000
    },
    {
        id:4,
        image:"images/eveningshimmerclutch.avif",
        name:"bag",
        price:20000
    },
    {
        id:5,
        image:"images/purse.webp",
        name:"bag",
        price:20000
    },
    {
        id:6,
        image:"images/katespade.jpg",
        name:"bag",
        price:20000
    },
    {
        id:7,
        image:"images/bags.webp",
        name:"bag",
        price:20000
    },
    {
         id:8,
         image:"images/shoe8.jpg",
         name:"bag",
         price:20000
    },
    {
        id:9,
        image:"images/shoe1.jfif",
        name:"bag",
        price:20000
    },
    {
        id:10,
        image:"images/shoe2.jfif",
        name:"bag",
        price:20000
    },
    {
        id:11,
        image:"images/shoe3.jfif",
        name:"bag",
        price:20000
    },
    {
        id:12,
        image:"images/shoe4.jfif",
        name:"bag",
        price:20000
    },
    {
        id:13,
        image:"images/shoe5.jfif",
        name:"bag",
        price:20000
    },
    {
        id:14,
        image:"images/shoe6.jfif",
        name:"bag",
        price:20000
    },
    {
        id:15,
        image:"images/shoe7.jfif",
        name:"bag",
        price:20000
    },
    {
        id:16,
        image:"images/ring.jfif",
        name:"bag",
        price:20000
    },
    {
        id:17,
        image:"images/14kgoldropechain.jfif",
        name:"bag",
        price:20000
    },
    {
        id:18,
        image:"images/ear2.jfif",
        name:"bag",
        price:20000
    },
    {
        id:19,
        image:"images/earring.jfif",
        name:"bag",
        price:20000
    },
    {
        id:20,
        image:"images/simplegoldheart.webp",
        name:"bag",
        price:20000
    },
    {
        id:21,
        image:"images/stonelinkanthro.webp",
        name:"bag",
        price:20000
    },{
    
        id:22,
        image:"images/teardropemerald.webp",
        name:"bag",
        price:20000
    },
    {
        id:23,
        image:"images/vintagelondonpink.jfif",
        name:"bag",
        price:20000
    }];